server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #    password: 123456
    password: Yanjin
    url: jdbc:mysql://localhost:3306/filemanager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
shiro:
  ## shiro内置的登录认证校验过滤器，校验后发现没有登录认证，跳转的资源地址（登录页）
  loginUrl: /myController/login